FROM golang:alpine

RUN apk add --no-cache make curl gcc libc-dev
ENV GO111MODULE=on
WORKDIR /app/
COPY go.mod .
COPY go.sum .

RUN go mod download
COPY . .
WORKDIR /app/cmd
CMD go test -v -tags=integration ./...